spring.application.name=spars_server

spring.datasource.url=jdbc:mysql://srv674.hstgr.io:3306/u705414379_spars_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=u705414379_spars_admin
spring.datasource.password=ZTu2f7jj8lH&
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=ChangeThisSecretKeyToAStrongBase64EncodedSecretForHS256ChangeThisSecretKey
jwt.expiration-ms=86400000
